/**
 * Realistic demo portfolio used when Supabase is not configured
 * or when the user clicks "Load demo portfolio".
 * Engineered for concentration risk, a behind-schedule goal, and macro relevance.
 */
import type { HoldingRow, PortfolioSummary, Goal, Profile } from "@/types";

export const DEMO_PROFILE: Profile = {
  id: "demo-user",
  full_name: "Aarav Sharma",
  risk_tolerance: "moderate",
  investment_horizon: "long",
  primary_goal: "House down-payment",
  monthly_investment_capacity: 40000,
  onboarding_complete: true,
};

export const DEMO_GOALS: Goal[] = [
  {
    id: "goal-1",
    name: "House down-payment",
    target_amount: 4500000,
    current_amount: 1120000,
    target_date: "2030-06-01",
    priority: 1,
    status: "active",
  },
];

export const DEMO_HOLDINGS: HoldingRow[] = [
  {
    holding_id: "h1",
    portfolio_id: "p1",
    asset_id: "a1",
    symbol: "RELIANCE",
    name: "Reliance Industries",
    asset_class: "equity",
    asset_subtype: "large_cap",
    data_source: "live",
    quantity: 45,
    average_buy_price: 2450,
    current_price: 2980,
    current_value: 134100,
    liquidity: "high",
    expected_return_annual: 12,
    volatility_annual: 18,
    maturity_date: null,
    coupon_rate: null,
    interest_rate: null,
    tenure_months: null,
  },
  {
    holding_id: "h2",
    portfolio_id: "p1",
    asset_id: "a2",
    symbol: "TCS",
    name: "Tata Consultancy Services",
    asset_class: "equity",
    asset_subtype: "large_cap",
    data_source: "live",
    quantity: 30,
    average_buy_price: 3200,
    current_price: 3850,
    current_value: 115500,
    liquidity: "high",
    expected_return_annual: 11,
    volatility_annual: 16,
    maturity_date: null,
    coupon_rate: null,
    interest_rate: null,
    tenure_months: null,
  },
  {
    holding_id: "h3",
    portfolio_id: "p1",
    asset_id: "a3",
    symbol: "HDFCBANK",
    name: "HDFC Bank",
    asset_class: "equity",
    asset_subtype: "large_cap",
    data_source: "live",
    quantity: 80,
    average_buy_price: 1450,
    current_price: 1680,
    current_value: 134400,
    liquidity: "high",
    expected_return_annual: 10,
    volatility_annual: 17,
    maturity_date: null,
    coupon_rate: null,
    interest_rate: null,
    tenure_months: null,
  },
  {
    holding_id: "h4",
    portfolio_id: "p1",
    asset_id: "a4",
    symbol: "INFY",
    name: "Infosys",
    asset_class: "equity",
    asset_subtype: "large_cap",
    data_source: "live",
    quantity: 60,
    average_buy_price: 1400,
    current_price: 1720,
    current_value: 103200,
    liquidity: "high",
    expected_return_annual: 11,
    volatility_annual: 17,
    maturity_date: null,
    coupon_rate: null,
    interest_rate: null,
    tenure_months: null,
  },
  {
    holding_id: "h5",
    portfolio_id: "p1",
    asset_id: "a5",
    symbol: "NIFTYBEES",
    name: "Nippon India Nifty BeES",
    asset_class: "etf",
    asset_subtype: null,
    data_source: "live",
    quantity: 500,
    average_buy_price: 210,
    current_price: 255,
    current_value: 127500,
    liquidity: "high",
    expected_return_annual: 11,
    volatility_annual: 15,
    maturity_date: null,
    coupon_rate: null,
    interest_rate: null,
    tenure_months: null,
  },
  {
    holding_id: "h6",
    portfolio_id: "p1",
    asset_id: "a6",
    symbol: "PARAGPARIKH",
    name: "Parag Parikh Flexi Cap Fund",
    asset_class: "mutual_fund",
    asset_subtype: "flexi_cap",
    data_source: "live",
    quantity: 3200,
    average_buy_price: 55,
    current_price: 72,
    current_value: 230400,
    liquidity: "medium",
    expected_return_annual: 13,
    volatility_annual: 14,
    maturity_date: null,
    coupon_rate: null,
    interest_rate: null,
    tenure_months: null,
  },
  {
    holding_id: "h7",
    portfolio_id: "p1",
    asset_id: "a7",
    symbol: "SBI-FD-3Y",
    name: "SBI Fixed Deposit 3Y",
    asset_class: "fixed_deposit",
    asset_subtype: null,
    data_source: "mock",
    quantity: 1,
    average_buy_price: 200000,
    current_price: 200000,
    current_value: 200000,
    liquidity: "low",
    expected_return_annual: 6.8,
    volatility_annual: 1,
    maturity_date: "2028-03-15",
    coupon_rate: null,
    interest_rate: 6.8,
    tenure_months: 36,
  },
  {
    holding_id: "h8",
    portfolio_id: "p1",
    asset_id: "a8",
    symbol: "SGB",
    name: "Sovereign Gold Bond 2030",
    asset_class: "gold",
    asset_subtype: "sovereign",
    data_source: "mock",
    quantity: 50,
    average_buy_price: 5200,
    current_price: 6850,
    current_value: 342500,
    liquidity: "medium",
    expected_return_annual: 8,
    volatility_annual: 12,
    maturity_date: "2030-08-01",
    coupon_rate: 2.5,
    interest_rate: null,
    tenure_months: null,
  },
  {
    holding_id: "h9",
    portfolio_id: "p1",
    asset_id: "a9",
    symbol: "EMBASSY",
    name: "Embassy Office Parks REIT",
    asset_class: "reit",
    asset_subtype: null,
    data_source: "mock",
    quantity: 200,
    average_buy_price: 380,
    current_price: 365,
    current_value: 73000,
    liquidity: "medium",
    expected_return_annual: 7.5,
    volatility_annual: 14,
    maturity_date: null,
    coupon_rate: null,
    interest_rate: null,
    tenure_months: null,
  },
  {
    holding_id: "h10",
    portfolio_id: "p1",
    asset_id: "a10",
    symbol: "IRBINVIT",
    name: "IRB InvIT Fund",
    asset_class: "invit",
    asset_subtype: null,
    data_source: "mock",
    quantity: 400,
    average_buy_price: 105,
    current_price: 98,
    current_value: 39200,
    liquidity: "medium",
    expected_return_annual: 8,
    volatility_annual: 13,
    maturity_date: null,
    coupon_rate: null,
    interest_rate: null,
    tenure_months: null,
  },
  {
    holding_id: "h11",
    portfolio_id: "p1",
    asset_id: "a11",
    symbol: "GSEC2034",
    name: "7.18% GS 2034",
    asset_class: "bond",
    asset_subtype: "gsec",
    data_source: "mock",
    quantity: 50,
    average_buy_price: 1020,
    current_price: 1015,
    current_value: 50750,
    liquidity: "medium",
    expected_return_annual: 7.1,
    volatility_annual: 5,
    maturity_date: "2034-07-24",
    coupon_rate: 7.18,
    interest_rate: null,
    tenure_months: null,
  },
];

export function buildDemoSummary(): PortfolioSummary {
  const holdings = DEMO_HOLDINGS;
  const totalValue = holdings.reduce((s, h) => s + h.current_value, 0);
  const totalInvested = holdings.reduce(
    (s, h) => s + h.quantity * (h.average_buy_price || 0),
    0
  );
  const absoluteReturn = totalValue - totalInvested;
  const absoluteReturnPct = totalInvested > 0 ? (absoluteReturn / totalInvested) * 100 : 0;

  const byClass: Record<string, number> = {};
  holdings.forEach((h) => {
    byClass[h.asset_class] = (byClass[h.asset_class] || 0) + h.current_value;
  });

  const allocation = Object.entries(byClass)
    .map(([name, value]) => ({
      name: name,
      value,
      percentage: totalValue > 0 ? (value / totalValue) * 100 : 0,
    }))
    .sort((a, b) => b.value - a.value);

  const skewed = allocation.find((a) => a.percentage > 60);

  return {
    totalValue,
    totalInvested,
    absoluteReturn,
    absoluteReturnPct,
    allocation: allocation.map((a) => ({
      ...a,
      name: a.name.replace(/_/g, " "),
    })),
    isSkewed: !!skewed,
    skewedClass: skewed ? skewed.name.replace(/_/g, " ") : null,
    holdings,
    portfolioId: "p1",
  };
}

export const DEMO_MACRO = {
  as_of: "2026-07-20",
  repo_rate: 6.5,
  inflation_cpi: 4.8,
  inflation_trend: "stable",
  liquidity_condition: "neutral",
  market_cycle: "mid_cycle",
  equity_valuation: "fair",
  bond_yield_10y: 7.05,
  usd_inr: 83.5,
  notes:
    "RBI on pause, inflation within tolerance band, liquidity comfortable. Global risk sentiment mixed.",
};

export const DEMO_ASSETS_CATALOGUE = [
  ...DEMO_HOLDINGS.map((h) => ({
    id: h.asset_id,
    symbol: h.symbol,
    name: h.name,
    asset_class: h.asset_class,
    asset_subtype: h.asset_subtype,
    expected_return_annual: h.expected_return_annual,
    volatility_annual: h.volatility_annual,
    liquidity: h.liquidity,
    data_source: h.data_source,
    issuer: null as string | null,
    expense_ratio: null as number | null,
  })),
  {
    id: "extra-1",
    symbol: "MINDSPACE",
    name: "Mindspace Business Parks REIT",
    asset_class: "reit",
    asset_subtype: null,
    expected_return_annual: 7.2,
    volatility_annual: 13,
    liquidity: "medium" as const,
    data_source: "mock" as const,
    issuer: "K Raheja",
    expense_ratio: null,
  },
  {
    id: "extra-2",
    symbol: "ICICI-FD",
    name: "ICICI Bank FD 5Y",
    asset_class: "fixed_deposit",
    asset_subtype: null,
    expected_return_annual: 7.0,
    volatility_annual: 1,
    liquidity: "low" as const,
    data_source: "mock" as const,
    issuer: "ICICI Bank",
    expense_ratio: null,
  },
  {
    id: "extra-3",
    symbol: "GOLDBEES",
    name: "Nippon India Gold BeES",
    asset_class: "gold",
    asset_subtype: "etf",
    expected_return_annual: 8,
    volatility_annual: 12,
    liquidity: "high" as const,
    data_source: "live" as const,
    issuer: null,
    expense_ratio: 0.75,
  },
];
